# See [Connector Acceptance Tests](https://docs.airbyte.com/connector-development/testing-connectors/connector-acceptance-tests-reference)
# for more information about how to configure these tests
connector_image: airbyte/source-google-ads:dev
test_strictness_level: high
acceptance_tests:
  spec:
    tests:
      - spec_path: "source_google_ads/spec.json"
  connection:
    tests:
      - config_path: "secrets/config.json"
        status: "succeed"
      - config_path: "integration_tests/invalid_config.json"
        status: "exception"
  discovery:
    tests:
      - config_path: "secrets/config.json"
  basic_read:
    tests:
      - config_path: "secrets/config.json"
        expect_records:
          path: "integration_tests/expected_records.jsonl"
        timeout_seconds: 3600
        empty_streams:
          - name: "account_labels"
            bypass_reason: "Unsufficient permissions"
          - name: "unhappytable"
            bypass_reason: "Empty testing stream"
          - name: "shopping_performance_report"
            bypass_reason: "Stream not filled yet."
          - name: "display_topics_performance_report"
            bypass_reason: "Next config"
          - name: "click_view"
            bypass_reason: "Next config"
          - name: "change_status"
            bypass_reason: "Next config"
        ignored_fields:
          accounts:
            - name: customer.optimization_score_weight
              bypass_reason: "can be updated, also it is sometimes integer, sometimes float"
            - name: customer.optimization_score
              bypass_reason: "value can be changed because it is real-life recommendation from Amazon"
      - config_path: "secrets/config_click_view.json"
        expect_records:
          path: "integration_tests/expected_records_click.jsonl"
        timeout_seconds: 600
        empty_streams:
          - name: "account_performance_report"
            bypass_reason: "Floating data"
          - name: "accounts"
            bypass_reason: "Floating data"
          - name: "ad_group_ad_labels"
            bypass_reason: "Stream not filled yet."
          - name: "ad_group_ad_report"
            bypass_reason: "Unable to seed the stream"
          - name: "ad_group_ads"
            bypass_reason: "Unable to seed the stream"
          - name: "ad_group_bidding_strategies"
            bypass_reason: "Stream not filled yet."
          - name: "ad_group_criterion_labels"
            bypass_reason: "Stream not filled yet."
          - name: "ad_group_criterions"
            bypass_reason: "Stream not filled yet."
          - name: "ad_group_custom"
            bypass_reason: "Stream not filled yet."
          - name: "ad_group_labels"
            bypass_reason: "Stream not filled yet."
          - name: 'ad_groups'
            bypass_reason: "Stream not filled yet."
          - name: 'ad_listing_group_criterions'
            bypass_reason: "Stream not filled yet."
          - name: 'audience'
            bypass_reason: "Stream not filled yet."
          - name: 'campaign_bidding_strategies'
            bypass_reason: "Stream not filled yet."
          - name: 'campaign_budget'
            bypass_reason: "Stream not filled yet."
          - name: 'campaign_labels'
            bypass_reason: "Stream not filled yet."
          - name: 'campaigns'
            bypass_reason: "Stream not filled yet."
          - name: 'custom_audience'
            bypass_reason: "Stream not filled yet."
          - name: 'display_keyword_performance_report'
            bypass_reason: "Stream not filled yet."
          - name: 'geographic_report'
            bypass_reason: "Stream not filled yet."
          - name: 'happytable'
            bypass_reason: "Stream not filled yet."
          - name: 'keyword_report'
            bypass_reason: "Stream not filled yet."
          - name: "labels"
            bypass_reason: "Stream not filled yet."
          - name: 'user_interest'
            bypass_reason: "Stream not filled yet."
          - name: 'user_location_report'
            bypass_reason: "Stream not filled yet."
          - name: "display_topics_performance_report"
            bypass_reason: "Stream not filled yet."
          - name: "account_labels"
            bypass_reason: "Unable to seed the stream"
          - name: "unhappytable"
            bypass_reason: "Stream not filled yet."
          - name: "shopping_performance_report"
            bypass_reason: "Stream not filled yet."
          - name: "ad_group_ad_report"
            bypass_reason: "Stream not filled yet."
          - name: "campaign_criterion"
            bypass_reason: "Next config"
          - name: "change_status"
            bypass_reason: "Next config"
      - config_path: "secrets/config_change_status.json"
        expect_records:
          path: "integration_tests/expected_records_change_status.jsonl"
        timeout_seconds: 600
        empty_streams:
          - name: "account_performance_report"
            bypass_reason: "Floating data"
          - name: "accounts"
            bypass_reason: "Floating data"
          - name: "ad_group_ad_labels"
            bypass_reason: "Stream not filled yet."
          - name: "ad_group_ad_report"
            bypass_reason: "Unable to seed the stream"
          - name: "ad_group_ads"
            bypass_reason: "Unable to seed the stream"
          - name: "ad_group_bidding_strategies"
            bypass_reason: "Stream not filled yet."
          - name: "ad_group_criterion_labels"
            bypass_reason: "Stream not filled yet."
          - name: "ad_group_criterions"
            bypass_reason: "Stream not filled yet."
          - name: "ad_group_custom"
            bypass_reason: "Stream not filled yet."
          - name: "ad_group_labels"
            bypass_reason: "Stream not filled yet."
          - name: 'ad_groups'
            bypass_reason: "Stream not filled yet."
          - name: 'ad_listing_group_criterions'
            bypass_reason: "Stream not filled yet."
          - name: 'audience'
            bypass_reason: "Stream not filled yet."
          - name: 'campaign_bidding_strategies'
            bypass_reason: "Stream not filled yet."
          - name: 'campaign_budget'
            bypass_reason: "Stream not filled yet."
          - name: 'campaign_labels'
            bypass_reason: "Stream not filled yet."
          - name: 'campaigns'
            bypass_reason: "Stream not filled yet."
          - name: 'custom_audience'
            bypass_reason: "Stream not filled yet."
          - name: 'display_keyword_performance_report'
            bypass_reason: "Stream not filled yet."
          - name: 'geographic_report'
            bypass_reason: "Stream not filled yet."
          - name: 'happytable'
            bypass_reason: "Stream not filled yet."
          - name: 'keyword_report'
            bypass_reason: "Stream not filled yet."
          - name: "labels"
            bypass_reason: "Stream not filled yet."
          - name: 'user_interest'
            bypass_reason: "Stream not filled yet."
          - name: 'user_location_report'
            bypass_reason: "Stream not filled yet."
          - name: "account_labels"
            bypass_reason: "Unable to seed the stream"
          - name: "unhappytable"
            bypass_reason: "Stream not filled yet."
          - name: "shopping_performance_report"
            bypass_reason: "Stream not filled yet."
          - name: "ad_group_ad_report"
            bypass_reason: "Stream not filled yet."
          - name: "click_view"
            bypass_reason: "Next config"
          - name: "campaign_criterion"
            bypass_reason: "Next config"
          - name: "ad_group_criterions"
            bypass_reason: "Next config"
  full_refresh:
    tests:
      - config_path: "secrets/config.json"
        configured_catalog_path: "integration_tests/configured_catalog.json"
  incremental:
    tests:
      - config_path: "secrets/incremental_config.json"
        configured_catalog_path: "integration_tests/incremental_catalog.json"
        threshold_days: 14
        future_state:
          future_state_path: "integration_tests/abnormal_state.json"
        cursor_paths:
          account_performance_report: ["4651612872", "segments.date"]
          click_view: ["4651612872", "segments.date"]
          geographic_report: ["4651612872", "segments.date"]
          keyword_report: ["4651612872", "segments.date"]
          display_topics_performance_report: ["4651612872", "segments.date"]
          shopping_performance_report: ["4651612872", "segments.date"]
          ad_group_ads: ["4651612872", "segments.date"]
          ad_groups: ["4651612872", "segments.date"]
          accounts: ["4651612872", "segments.date"]
          campaigns: ["4651612872", "segments.date"]
          campaign_budget: ["4651612872", "segments.date"]
          user_location_report: ["4651612872", "segments.date"]
          ad_group_ad_report: ["4651612872", "segments.date"]
          display_keyword_performance_report: ["4651612872", "segments.date"]
          ad_group_criterions: [ "change_status", "4651612872", "change_status.last_change_date_time" ]
          campaign_criterion: [ "change_status", "4651612872", "change_status.last_change_date_time" ]
          change_status: ["4651612872", "change_status.last_change_date_time"]
